# Generated by Django 4.2.7 on 2023-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, upload_to='photo/')),
                ('open_hour', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=50)),
                ('latitude', models.DecimalField(decimal_places=17, max_digits=20)),
                ('longitude', models.DecimalField(decimal_places=17, max_digits=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
