# Generated by Django 4.2.7 on 2023-11-07 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_restaurants_open_hour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='open_hour',
            new_name='opening_hours',
        ),
    ]
