# Generated by Django 4.2.7 on 2023-11-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_open_hour_restaurants_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='opening_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
